# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string_format is passed to datetime.strftime()
# timezone = UTC

# max length of characters to attribute to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported
# relative to the path of the alembic.ini file
# prepend_sys_path = true

# version location specification; this defaults
# to migrations/versions.  When using multiple version
# directories, paths must be separated by spaces or commas.
# version_locations = %(here)s/bar %(here)s/bat migrations/versions

# version path separator; as above, this can be some character.
# default is os.pathsep
# version_path_separator = :

# set to 'true' to search source files for Python
# subprocesses.  Note this can slow down start-up times.
# search_paths = false

# logging configuration is handled via logging.config.fileConfig
# but only if logconfig is present
# logconfig = logging.config.ini

# the backends.  Format is:
# sqlalchemy.url = driver://user:pass@host/dbname
# we load this dynamically in env.py from our Settings object!
sqlalchemy.url = postgresql://postgres:postgres@localhost/privacyshield

[post_write_hooks]
# post_write_hooks defines scripts or behavior that is run after a
# revision script is generated.

[logging]
# logging configuration
default = info
